<?php

namespace AppBundle\Repository;

/**
 * WatchListItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchListItemRepository extends \Doctrine\ORM\EntityRepository
{
}
